services:
  - type: web
    name: mydailypanel-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: GOOGLE_CLIENT_ID
        value: your_client_id
